Use known width and height of the shell instead of asking GDK.gdk_window_get_frame_extents (window, rect).
eclipse-platform/eclipse.platform.swt pull request #1165
Opened 2024-04-07 16:38 UTC by raghucssit

For GDK.gdk_window_get_frame_extents (window, rect) to return correct values shell should be open. Once SWT asks GTK to show the shell via Native calls it takes sometime to open the shell.
On high performance machines adjustTrip is asking GTK to give it width and height before it has completely opened the shell. This results in returning default size.(which is {0,0,1,1})
So We can use the height and width which we already know when opening the shell.

 Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1161

2024-04-07 20:01 UTC, raghucssit commented
Test Failure has started from here:
https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/master/508/

2024-04-09 14:41 UTC, iloveeclipse commented
The problem explanation makes sense for me.

However, I have my concerns regarding the patch.

- https://docs.gtk.org/gdk3/method.Window.get_frame_extents.html is supposed to do: `Obtains the bounding box of the window, **including** window manager titlebar/borders if any.`
- https://docs.gtk.org/gdk3/method.Window.resize.html doesn't say anything if the size is with or without trims: `Resizes window; for toplevel windows, asks the window manager to resize the window`

We replac also **unconditionally** code that used shell size including trims received (in good case) from window manager with **some** size we **ask** to set (but don't know the actual size as effect of the call).

What about to use the new arguments that you've added to the `adjustTrim()` **conditionally**, only if `gdk_window_get_frame_extents()`  returns garbage values (like in the error case we have)?

2024-04-09 18:02 UTC, raghucssit commented
> * doesn't say anything if the size is with or without trims: `Resizes window; for toplevel windows, asks the window manager to resize the window`

Yes. We can ask GTK for size if it returns default then we can use our passed values.

Similar problem was existed in the past. I found it was worked around like this,
https://github.com/eclipse-platform/eclipse.platform.swt/blob/5b437ee2bd8cdda7083a9f2ceeadb172a583ed37/bundles/org.eclipse.swt/Eclipse%20SWT/gtk/org/eclipse/swt/widgets/Shell.java#L2317

2024-04-10 09:10 UTC, raghucssit commented
> The problem explanation makes sense for me.
> 
> However, I have my concerns regarding the patch.
> 
> * https://docs.gtk.org/gdk3/method.Window.get_frame_extents.html is supposed to do: `Obtains the bounding box of the window, **including** window manager titlebar/borders if any.`
> * https://docs.gtk.org/gdk3/method.Window.resize.html doesn't say anything if the size is with or without trims: `Resizes window; for toplevel windows, asks the window manager to resize the window`
> 
> We replac also **unconditionally** code that used shell size including trims received (in good case) from window manager with **some** size we **ask** to set (but don't know the actual size as effect of the call).
> 
> What about to use the new arguments that you've added to the `adjustTrim()` **conditionally**, only if `gdk_window_get_frame_extents()` returns garbage values (like in the error case we have)?

I have pushed the change on this suggestion.
Now we use known width and height if gtk returns default values.

2024-04-10 16:51 UTC, iloveeclipse requested changes
I believe the patch is better now, see some improvement comments below.

2024-04-10 16:51 UTC, iloveeclipse commented on bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java
> + * adjustments are read from 'user/.swt.trims.prefs' for each trim style. If
`from 'user/` -> `from '$HOME/`

2024-04-10 16:51 UTC, iloveeclipse commented on bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java
> + * such a file does not exist then it uses default values initialized.
`then it uses default values initialized.` -> `then the trim values are queried from GTK`.

2024-04-10 16:51 UTC, iloveeclipse commented on bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java
> +	// ready. If Gtk returns window dimensions we can use it. See 1161
`If Gtk returns window dimensions we can use it.` 
->  
`If GTK returns window dimensions we can use it, if not, we will use "requested" shell size as returned by gtk_window_resize() in setVisible()`

`See 1161` -> `See https://github.com/eclipse-platform/eclipse.platform.swt/issues/1161`

2024-04-10 16:51 UTC, iloveeclipse commented on bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java
> +	if (rect.width > 1 || rect.height > 1) {
I believe this new block including comment should go **inside** the `if (!GTK.GTK4)` block above, as the bad values are returned only in this case.

2024-04-10 16:51 UTC, iloveeclipse commented on bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java
> +void adjustTrim (int curWidth, int curHeight) {
`curWidth, curHeight` - I believe we should name it `widthHint`and `heightHint`, as those are not necessarily the correct sizes (depends on actual trim)

2024-04-11 07:08 UTC, raghucssit commented
All review comments fixed.

2024-04-11 07:22 UTC, iloveeclipse approved these changes
Thanks, looks good now.

2024-04-11 09:29 UTC, iloveeclipse commented on bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java
> + * adjustments are read from '$HOME/.swt.trims.prefs' for each trim style. If
`$HOME/.swt.trims.prefs` -> `$HOME/.swt/trims.prefs`

2024-04-11 11:25 UTC, merged