Fix for #1288: No exception when creating GC with image from another thread
eclipse-platform/eclipse.platform.swt pull request #1289
Opened 2024-06-19 15:15 UTC by akoch-yatta

This commit fixes an issue when creating a GC from an Image using a device bound to another thread as the GC is currently created in.

2024-06-20 05:47 UTC, ddscharfe commented
Tested under Windows 11, I don't get an exception anymore

2024-06-20 10:54 UTC, fedejeanne requested changes

2024-06-20 10:54 UTC, fedejeanne commented on tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_GC.java
> +	}
No need to catch this one, throw it

2024-06-20 11:57 UTC, akoch-yatta commented on tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_GC.java
> +	}
Done

2024-06-21 08:56 UTC, fedejeanne approved these changes

2024-06-21 08:56 UTC, merged