add linux riscv64 build
eclipse-platform/eclipse.platform.swt pull request #1445
Opened 2024-09-04 15:38 UTC by yuzibo

2024-09-04 16:08 UTC, yuzibo commented
This is a part of fixing #1443. But I am not sure how to verify this until now, please tell me if any issues.

It seems the error from CI was the same with other architecture.

2024-09-05 00:31 UTC, yuzibo commented
Good news is that this can be built wit `mvn clean verify  -DskipTests=true` on riscv64 machines

2024-09-05 14:24 UTC, akurtakov requested changes
Other than the p2.inf changes the rest looks good. We can't get these parts in as they will break building repos by trying to put linux.riscv64 fragments in the repository but they will not be built. 
This should be totally irrelevant for builds that aim at riscv64.

2024-09-05 14:24 UTC, akurtakov commented on bundles/org.eclipse.swt/META-INF/p2.inf
> +
This can't go in now as there is no riscv64 fragment build by default.

2024-09-05 14:24 UTC, akurtakov commented on local-build/org.eclipse.swt.fragments.localbuild/META-INF/p2.inf
> +requires.8.namespace = org.eclipse.equinox.p2.iu
This can't go in now as there is no riscv64 fragment build by default.

2024-09-05 15:31 UTC, akurtakov approved these changes
Looks good now.

2024-09-05 15:32 UTC, yuzibo commented
> Other than the p2.inf changes the rest looks good. We can't get these parts in as they will break building repos by trying to put linux.riscv64 fragments in the repository but they will not be built. This should be totally irrelevant for builds that aim at riscv64.

Thanks for reviewing this. I over-referenced to add support eclipse from other architectures.

2024-09-05 15:40 UTC, yuzibo commented
> Looks good now.

Thanks for approving this.:)

Now I am get the FAILURE on riscv64 hardware, this is [log](https://gist.github.com/yuzibo/006dce0f4c0e849edca39e89cdfecb60). Could you give me some advice on the next steps which how to push the porting works. TIA.

2024-09-05 15:48 UTC, akurtakov commented
> > Looks good now.
> 
> Thanks for approving this.:)
> 
> Now I am still get the FAILURE on riscv64 hardware, this is [log](https://gist.github.com/yuzibo/006dce0f4c0e849edca39e89cdfecb60). Could you give me some advice on the next steps which how to push the porting works. TIA.

This log makes me believe that jna https://github.com/java-native-access/jna lacks freebsd.riscv64 support. If you look in https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar:META-INF/MANIFEST.MF you'll notice there is only com/sun/jna/freebsd-x8
 6/libjnidispatch.so; processor=x86;osname=freebsd, com/sun/jna/freebs
 d-x86-64/libjnidispatch.so; processor=x86-64;osname=freebsd

2024-09-05 15:51 UTC, merged

2024-09-05 15:57 UTC, yuzibo commented
> This log makes me believe that jna https://github.com/java-native-access/jna lacks freebsd.riscv64 support. If you look in https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar:META-INF/MANIFEST.MF you'll notice there is only com/sun/jna/freebsd-x8 6/libjnidispatch.so; processor=x86;osname=freebsd, com/sun/jna/freebs d-x86-64/libjnidispatch.so; processor=x86-64;osname=freebsd . You'll have to work with them to add support. You can use [java-native-access/jna#1578](https://github.com/java-native-access/jna/pull/1578) as an example where freebsd aarch64 was added.

Thanks, I will look at this.

2024-09-09 14:00 UTC, yuzibo commented
> This log makes me believe that jna https://github.com/java-native-access/jna lacks freebsd.riscv64 support. If you look in https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar:META-INF/MANIFEST.MF you'll notice there is only com/sun/jna/freebsd-x8 6/libjnidispatch.so; processor=x86;osname=freebsd, com/sun/jna/freebs d-x86-64/libjnidispatch.so; processor=x86-64;osname=freebsd . You'll have to work with them to add support. You can use [java-native-access/jna#1578](https://github.com/java-native-access/jna/pull/1578) as an example where freebsd aarch64 was added.

Thanks for the pointer again.

The issue has been confirmed from jna upstream also,  see the [PR](https://github.com/java-native-access/jna/pull/1623).

But a harder problem for me now is how can I replace this jna with the modified locally.

There is the [com.sun.jna](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target#L44C17-L44C28) with version defined. So can I comment out the line and put the jna updated into /$HOME/.m2/repository. From the  original build stack [log](https://gist.github.com/yuzibo/006dce0f4c0e849edca39e89cdfecb60), can I assume this jar is stored in /$HOME/.m2/repository/p2/osgi/bundle/com.sun.jna/5.14.0.v20231211-1200/ (or other place)?

Can this way work? 

TIA.

2024-09-09 14:38 UTC, akurtakov commented
@yuzibo I would go for local mvn install of fixed jna version (preferably with bumped version) and require that version in the target file otherwise you risk maven overriding after/when it sees checksums mismatch (I am not 100% sure here).