BorderLayout must pass the maximum width to control computation.
eclipse-platform/eclipse.platform.swt pull request #165
Opened 2022-05-24 08:11 UTC by laeubi

If components has not an intrinsic preferred size but can adapt to the
available space e.g. with wrapping, calling just their preferred size
without restrictions gives false results e.g. for the height.

Fix https://github.com/eclipse-platform/eclipse.platform.swt/issues/163

I know its late in the release, but still like to ask to get PMC approval to include this bugfix as it is very local and there is a unit test covering this area of code.

2022-05-24 12:39 UTC, niraj-modi requested changes
With this patch i notice below JUnit test failing:
Test_org_eclipse_swt_layout_BorderLayout#testHints()
-------------------------------------------------------------
java.lang.AssertionError: expected:<40> but was:<778>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_layout_BorderLayout.testHints(Test_org_eclipse_swt_layout_BorderLayout.java:76)
-------------------------------------------------------------

2022-05-24 12:43 UTC, laeubi commented
@niraj-modi thanks for the hint, any idea why the CI is not executing that test?

2022-05-24 13:18 UTC, niraj-modi commented
> @niraj-modi thanks for the hint, any idea why the CI is not executing that test?

Raised #167 to capture this, looks like I found the reason, will update shortly.

2022-05-24 13:20 UTC, laeubi commented
Thanks, it would be good to know if this changes make it to ail or if it has failed (silently) before, so I'll just wait your results and then rebase the change so we have a (failing) CI then here.

2022-05-24 14:13 UTC, niraj-modi commented
> I have rebased now, I see the test executed but not failing (on GH action):
> 
> > org.eclipse.swt.tests.junit.Test_org_eclipse_swt_layout_BorderLayout ‑ testControlExcluded
> > org.eclipse.swt.tests.junit.Test_org_eclipse_swt_layout_BorderLayout ‑ testControlLayout
> > org.eclipse.swt.tests.junit.Test_org_eclipse_swt_layout_BorderLayout ‑ testHints

Any idea why it passed here ?

> Lets wait for the Jenkins CI...

Ok, on Jenkins CI this particular JUnit failure is noticed:
https://ci.eclipse.org/platform/job/eclipse.platform.swt/job/PR-165/2/testReport/org.eclipse.swt.tests.junit/Test_org_eclipse_swt_layout_BorderLayout/testHints/

2022-05-24 14:37 UTC, laeubi commented
Test is enhanced (and should pass now).

2022-05-25 05:47 UTC, niraj-modi approved these changes
Thanks for the quick update, changes look good now.
Change is specific to BorderLayout, hence approving for RC1.

2022-05-25 05:48 UTC, merged

2022-05-25 06:09 UTC, laeubi commented
Thanks for the review and approval!

2022-05-25 08:05 UTC, lshanmug reviewed
+1 for RC1

2022-05-25 09:18 UTC, niraj-modi commented
> > I have rebased now, I see the test executed but not failing (on GH action):
> > > org.eclipse.swt.tests.junit.Test_org_eclipse_swt_layout_BorderLayout ‑ testControlExcluded
> > > org.eclipse.swt.tests.junit.Test_org_eclipse_swt_layout_BorderLayout ‑ testControlLayout
> > > org.eclipse.swt.tests.junit.Test_org_eclipse_swt_layout_BorderLayout ‑ testHints
> 
> Any idea why it passed here ?
> 
> > Lets wait for the Jenkins CI...
> 
> Ok, on Jenkins CI this particular JUnit failure is noticed: https://ci.eclipse.org/platform/job/eclipse.platform.swt/job/PR-165/2/testReport/org.eclipse.swt.tests.junit/Test_org_eclipse_swt_layout_BorderLayout/testHints/

Captured above problem on issue #170
Note: Nothing urgent, but some scope of improvement to bring Github actions at par with Jenkins CI.