Issue #457 - Broken scaling on WSLg
eclipse-platform/eclipse.platform.swt pull request #461
Opened 2022-11-09 19:08 UTC by SyntevoAlex

To my understanding, all modern Linux supported by SWT shall use cairo auto scaling. KDE-based KUbuntu 18.04, where this wasn't the case, is no longer supported.

See also Bug 569233, which intends (not yet merged) to remove support for non-auto-scaling.

2022-11-09 19:10 UTC, SyntevoAlex commented
@sravanlakkimsetti if you like, this can wait until 4.27 Eclipse release cycle.
Note that this is related to Bug 569233, which is not merged yet.

2022-11-10 05:41 UTC, sravanlakkimsetti commented
I believe this can be merged in RC1. But the cleanup of dead code because of this change can wait till 4.27. @akurtakov what do you think?

2022-11-10 05:42 UTC, sravanlakkimsetti requested changes
There are unused imports. Please remove them before merge.

2022-11-13 14:29 UTC, SyntevoAlex commented
> There are unused imports.

Done.

> But the cleanup of dead code because of this change can wait till 4.27

Do you mean cleanup in this patch, or the other patches such as Bug 569233 ?

2022-11-14 05:51 UTC, sravanlakkimsetti commented
> Do you mean cleanup in this patch, or the other patches such as Bug 569233 ?

other patches like Bug 569233

2022-11-14 09:04 UTC, sravanlakkimsetti approved these changes

2022-11-14 09:08 UTC, sravanlakkimsetti commented
@SyntevoAlex Can you please verify whether this test is passing locally with 100% screen org.eclipse.swt.tests.junit.Test_org_eclipse_swt_custom_StyledText.test_caretSizeAndPositionVariableGlyphMetrics

2022-11-15 08:14 UTC, akurtakov commented
This test is long failing on verification builds and I haven't found what causes it.

2022-11-15 08:16 UTC, merged

2022-11-17 20:09 UTC, SyntevoAlex commented
Thanks for handling the PR!