[win32] ToolBar gets resized when mixing ToolItems with text and icon eclipse-platform/eclipse.platform.ui#443
eclipse-platform/eclipse.platform.swt pull request #499
Opened 2022-12-13 11:05 UTC by Christopher-Hermann

Fix for issue eclipse-platform/eclipse.platform.ui#443

2022-12-15 13:34 UTC, Christopher-Hermann commented
Test is also failing in master, not related to the changes in this PR.
https://ci.eclipse.org/platform/job/eclipse.platform.swt/job/master/726/

2022-12-15 15:51 UTC, vogella commented
@sratz can you review?

2022-12-19 13:35 UTC, sratz requested changes

2022-12-19 13:35 UTC, sratz commented on bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ToolBar.java
> +			for (ToolItem item : items) {
if a SINGLE toolbar item has both image + text we do not want to do this condensing.

2022-12-29 13:05 UTC, marcushoepfner commented
Regarding the failing test Test_org_eclipse_swt_custom_StyledText.test_caretSizeAndPositionVariableGlyphMetrics

It is this assert:
`assertEquals(text.getLineHeight(0) - text.getCaret().getSize().y, text.getCaret().getBounds().y);`

On my Mac locally this is:
text.getLineHeight(0):103
text.getCaret().getSize().y:16
text.getCaret().getBounds().y:87

The jenkins is a linux where the values are:
text.getLineHeight(0):104
text.getCaret().getSize().y:19
text.getCaret().getBounds().y:170

As you can see here: https://ci.eclipse.org/platform/job/eclipse.platform.swt/job/PR-517/lastCompletedBuild/testReport/org.eclipse.swt.tests.junit/Test_org_eclipse_swt_custom_StyledText/test_caretSizeAndPositionVariableGlyphMetrics/

Is the assert wrong or is the productive code having issues on Linux?

2022-12-29 13:33 UTC, marcushoepfner commented
> Regarding the failing test Test_org_eclipse_swt_custom_StyledText.test_caretSizeAndPositionVariableGlyphMetrics
> 
> It is this assert: `assertEquals(text.getLineHeight(0) - text.getCaret().getSize().y, text.getCaret().getBounds().y);`
> 
> On my Mac locally this is: text.getLineHeight(0):103 text.getCaret().getSize().y:16 text.getCaret().getBounds().y:87
> 
> The jenkins is a linux where the values are: text.getLineHeight(0):104 text.getCaret().getSize().y:19 text.getCaret().getBounds().y:170
> 
> As you can see here: https://ci.eclipse.org/platform/job/eclipse.platform.swt/job/PR-517/lastCompletedBuild/testReport/org.eclipse.swt.tests.junit/Test_org_eclipse_swt_custom_StyledText/test_caretSizeAndPositionVariableGlyphMetrics/
> 
> Is the assert wrong or is the productive code having issues on Linux?

The bounds of the caret are set via:
`Thread [main] (Suspended (breakpoint at line 323 in Caret))	
	Caret.setBounds(int, int, int, int) line: 323	
	StyledText.setCaretLocations(Point[], int) line: 8524	
	StyledText.setCaretLocations() line: 8439	
	StyledText.setStyleRanges(int, int, int[], StyleRange[], boolean) line: 10230	
	StyledText.setStyleRange(StyleRange) line: 10038	
	Test_org_eclipse_swt_custom_StyledText.test_caretSizeAndPositionVariableGlyphMetrics() line: 4878	
  [...]`
where as Caret.setBounds(int, int, int, int) is called with 2, 87, 0, 16

@mickaelistria is that something you could kindly check?

2023-01-05 12:26 UTC, akurtakov commented
Failing test is linux specific and known failure so please ignore for this patch.

2023-01-09 10:57 UTC, sratz approved these changes
The precondition should be specific enough to not have any side-effects in other situations.

So this looks good to me.

2023-01-09 11:00 UTC, merged