fix: #885 make R_29 builds succeed again.
eclipse-platform/eclipse.platform.swt pull request #886
Opened 2023-11-11 20:54 UTC by the-snowwhite

2023-11-11 20:59 UTC, merks requested changes
It's incorrectly incremented.

2023-11-11 20:59 UTC, merks commented on bundles/org.eclipse.swt/META-INF/MANIFEST.MF
> +Bundle-Version: 3.125.100.qualifier
Recall I said increment the third segment but here you incremented the second segment.

You'll probably want  to read this:

https://wiki.eclipse.org/Version_Numbering

2023-11-11 21:36 UTC, the-snowwhite commented
The purpose of fixing the build is not to afterwards enable a PR merge with new functionality.
The Purpose is enabling the #858 method.
That means a PR does not lead to merges but only to being able to fetch build artifacts after a successful build.
Then the PR is closed again without a merge.
I do not see anything in https://wiki.eclipse.org/Version_Numbering that covers that use case.
Am I wrong ?

2023-11-11 21:44 UTC, the-snowwhite commented
@merks 
Also 3.124.200 is already taken See here:
https://ci.eclipse.org/releng/job/eclipse.platform.swt/view/change-requests/job/PR-883/lastSuccessfulBuild/artifact/eclipse.platform.swt.binaries/bundles/org.eclipse.swt.gtk.linux.x86_64/target/

So the last logical option is:
3.124.110 ?

2023-11-11 21:58 UTC, merks commented
I thought explaining +1 on the third segment was pretty clear.  I was on an IPhone so it wasn't easy to tell you exactly what the number should be, given I didn't know the actual value.  

If the value is x.y.z.qualifier, then the next one would be x.y.z+1.qualifier and here z = 100.  The reason why the development stream does +100 service segment increments is to leave a large gap for many+1 increments to that service segment in a service stream.  That article I linked tries to explain that, but you saw little value there. You first incremented the second segment, not the third and now propose incrementing the third segment by 10.    😕 

Note that you do generate a significant volume of emails.  It's somewhat tempting to leave answers to someone else, so that I don't end up with a long chain of follow up emails.  No offense intended.  It's just an observation and something to consider.

2023-11-11 23:59 UTC, the-snowwhite commented
> I thought explaining +1 on the third segment was pretty clear. I was on an IPhone so it wasn't easy to tell you exactly what the number should be, given I didn't know the actual value.
> 
> If the value is x.y.z.qualifier, then the next one would be x.y.z+1.qualifier and here z = 100. The reason why the development stream does +100 service segment increments is to leave a large gap for many+1 increments to that service segment in a service stream. That article I linked tries to explain that, but you saw little value there. You first incremented the second segment, not the third and now propose incrementing the third segment by 10. 😕
> 
> Note that you do generate a significant volume of emails. It's somewhat tempting to leave answers to someone else, so that I don't end up with a long chain of follow up emails. No offense intended. It's just an observation and something to consider.

Sorry for the clutter in your inbox generated by me.
I do not know how your notification system works.
But i only get e-mails when someone mentions me.
Do you get more that that ?

Im not sure if altering the only way to go.
`Bundle-Version: 3.124.100.qualifier`

Finding a way to skip the mvn commands the require that would be better.
For this purpose only the last 2 mvn commands in the build log are needed.

2023-11-12 00:56 UTC, the-snowwhite commented
`Bundle-Version: 3.124.101.qualifier`
Is what is in the current PR and it has been running for hours ....
https://github.com/eclipse-platform/eclipse.platform.swt/pull/886/files

2023-11-12 06:22 UTC, laeubi commented
Just note that PRs are not the way to get an artifact for local build, you should instead build it locally using maven+ant and the native build toolchain.

For that purpose look into what the `Jenkins` file does to get some hints on how to compile locally, there you then can increase version (for test) like you desire and only need to rebuild small portions of the code, so no need to trigger a full build.

2023-11-12 07:28 UTC, the-snowwhite commented
@laeubi 
please look at the new feature request #888 
Im now closing this PR

2023-11-12 07:28 UTC, closed without merging