resolveTextDirection using Character.getDirectionality (solves #90)
eclipse-platform/eclipse.platform.swt pull request #91
Opened 2022-05-04 06:53 UTC by jukzi

prevent slow systemcalls for every character

2022-05-04 07:00 UTC, niraj-modi requested changes

2022-05-04 07:23 UTC, niraj-modi commented on bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/BidiUtil.java
> +			return SWT.LEFT_TO_RIGHT;
Try below relevant scenarios for testing MIX of English and RTL in single line:
1. https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/tests/org.eclipse.swt.tests.win32/ManualTests/org/eclipse/swt/tests/win32/snippets/Bug579626_English_ArabicTest.java
2. Opening above file source-code in Eclipse self-hosted mode.
3. Output of above file on console in Eclipse self-hosted mode.

2022-05-04 08:21 UTC, jukzi commented on bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/BidiUtil.java
> +			return SWT.LEFT_TO_RIGHT;
@niraj-modi it sounds like you know more about Bidi then me. Could you please take over and use my commit as an rough draft on how we could improve performance?
I will also don't have time nor hardware to adapt/test it n other hardware.

2022-05-06 08:43 UTC, jukzi commented
@niraj-modi do you plan to work on it or otherwise review my correction?

2022-05-06 09:42 UTC, niraj-modi requested changes
Did a quick test with the Mix of English and RTL characters, it work fine.
Please see inline for code improvements.

2022-05-06 09:42 UTC, niraj-modi commented on bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/BidiUtil.java
> +public static int getStrongDirection(byte directionality) {
This method should be non-public, default access should be fine:
static int getStrongDirection(byte directionality)

2022-05-06 09:42 UTC, niraj-modi commented on bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/BidiUtil.java
> +		return SWT.RIGHT_TO_LEFT;// Strong bidirectional character type "AL" in the Unicode specification.
Less code here, like below:
case Character.DIRECTIONALITY_RIGHT_TO_LEFT:
case Character.DIRECTIONALITY_RIGHT_TO_LEFT_ARABIC:
	return SWT.RIGHT_TO_LEFT;// Strong bidirectional character type "AL" in the Unicode specification.

2022-05-06 09:48 UTC, niraj-modi commented
@[Phillipus](https://github.com/Phillipus)
Hi Phil,
Can you try/test this improvement on BidiUtil.resolveTextDirection which uses Java capability now ?

2022-05-06 09:51 UTC, niraj-modi commented
> @niraj-modi do you plan to work on it or otherwise review my correction?

Thanks @jukzi for the revised PR, it's much improved now.
I have requested @[Phillipus](https://github.com/Phillipus) on help with further testing.

2022-05-06 14:03 UTC, jukzi commented
regarding performance: this changes reduces org.eclipse.debug.tests.console.IOConsoleTests.testBug421303_StreamProcessingDeadlock() from ~ 5sec to 0.3sec
see also https://github.com/eclipse-platform/eclipse.platform.debug/issues/5

2022-05-06 14:20 UTC, niraj-modi approved these changes
Latest code changes, looks good to me.

2022-05-06 14:21 UTC, merged

2022-05-06 14:22 UTC, niraj-modi commented
> @[Phillipus](https://github.com/Phillipus) Hi Phil, Can you try/test this improvement on BidiUtil.resolveTextDirection which uses Java capability now ?

We are still open to any feedback on this. Now changes can be directly tested in next Eclipse IBuild.